// This file is auto-generated by scripts/generate-logger-toggle-defaults.ts.
// Run `bun run generate:logger-toggles` to refresh it.

type LoggerToggleEntry =
	| boolean
	| {
			$self?: boolean
			[key: string]: LoggerToggleEntry | undefined
	  }

type LoggerToggleTree = Record<string, LoggerToggleEntry>

const LOGGER_TOGGLE_TREE = {
	app: false,
	'code-editor': {
		$self: false,
		clipboard: false,
		history: false
	},
	desktop: false,
	fs: false,
	perf: false,
	server: false,
	web: {
		$self: false,
		focus: false,
		prefetch: false,
		terminal: false
	}
} as const satisfies LoggerToggleTree

const LOGGER_TOGGLE_DEFAULTS = {
	app: false,
	'code-editor': false,
	'code-editor:clipboard': false,
	'code-editor:history': false,
	desktop: false,
	fs: false,
	perf: false,
	server: false,
	web: false,
	'web:focus': false,
	'web:prefetch': false,
	'web:terminal': false
} as const satisfies Record<string, boolean>

export { LOGGER_TOGGLE_DEFAULTS, LOGGER_TOGGLE_TREE }
