{
  "editor.fontSize": 14,
  "editor.fontFamily": "'JetBrains Mono Variable', monospace",
  "editor.cursorStyle": "line",
  "editor.tabSize": 4,
  "editor.wordWrap": false,
  "terminal.fontSize": 14,
  "terminal.fontFamily": "'JetBrains Mono Variable', monospace",
  "ui.fontSize": 13,
  "ui.fontFamily": "'Google Sans Flex', sans-serif",
  "appearance.theme": "dark",
  "appearance.sidebarWidth": 240,
  "appearance.showLineNumbers": true,
  "appearance.compactMode": false,
  "fonts.autoInstallPreview": true,
  "fonts.cacheLimit": 100,
  "fonts.previewText": "The quick brown fox jumps over the lazy dog 0123456789"
